/**
 * Configuration Management
 *
 * Loads configuration from multiple sources with priority (highest to lowest):
 * 1. CLI arguments
 * 2. Shell environment variables (export ESCRIBANO_*)
 * 3. ~/.escribano/.env file
 * 4. Default values
 *
 * Note: Project-level .env is NOT loaded by default (only for development).
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';
import { config as dotenvConfig } from 'dotenv';
import { z } from 'zod';

// =============================================================================
// CONFIG SCHEMA
// =============================================================================

const configSchema = z.object({
  // === PERFORMANCE ===
  frameWidth: z.number().int().min(320).max(3840).default(1024),
  vlmBatchSize: z.number().int().min(1).max(8).default(2),
  sampleInterval: z.number().int().min(1).max(60).default(10),

  // === QUALITY ===
  sceneThreshold: z.number().min(0).max(1).default(0.4),
  vlmMaxTokens: z.number().int().min(500).max(8000).default(2000),

  // === MODELS ===
  llmModel: z.string().optional(),
  llmBackend: z.enum(['mlx', 'ollama']).default('mlx'),
  llmMlxModel: z.string().optional(),
  vlmModel: z.string().default('mlx-community/Qwen3-VL-2B-Instruct-4bit'),
  subjectGroupingModel: z.string().optional(),

  // === DEBUGGING ===
  verbose: z.boolean().default(false),
  debugOllama: z.boolean().default(false),
  debugVlm: z.boolean().default(false),
  skipLlm: z.boolean().default(false),

  // === ADVANCED ===
  sceneMinInterval: z.number().int().min(1).max(10).default(2),
  sampleGapThreshold: z.number().int().min(5).max(60).default(15),
  sampleGapFill: z.number().int().min(1).max(10).default(3),
  mlxSocketPath: z.string().default('/tmp/escribano-mlx.sock'),
  mlxStartupTimeout: z.number().int().min(10000).default(60000),
  pythonPath: z.string().optional(),
  parallelTranscription: z.boolean().default(false),
  artifactThink: z.boolean().default(false),

  // === OPTIONAL (Outline publishing) ===
  outlineUrl: z.string().optional(),
  outlineToken: z.string().optional(),
  outlineCollection: z.string().default('Escribano Sessions'),
});

export type Config = z.infer<typeof configSchema>;

// =============================================================================
// DEFAULT CONFIG
// =============================================================================

const DEFAULT_CONFIG: Config = {
  frameWidth: 1024,
  vlmBatchSize: 2,
  sampleInterval: 10,
  sceneThreshold: 0.4,
  vlmMaxTokens: 2000,
  llmBackend: 'mlx',
  vlmModel: 'mlx-community/Qwen3-VL-2B-Instruct-4bit',
  verbose: false,
  debugOllama: false,
  debugVlm: false,
  skipLlm: false,
  sceneMinInterval: 2,
  sampleGapThreshold: 15,
  sampleGapFill: 3,
  mlxSocketPath: '/tmp/escribano-mlx.sock',
  mlxStartupTimeout: 60000,
  parallelTranscription: false,
  artifactThink: false,
  outlineCollection: 'Escribano Sessions',
};

// =============================================================================
// CONFIG FILE TEMPLATE
// =============================================================================

const CONFIG_TEMPLATE = `# Escribano Configuration - ~/.escribano/.env
# Generated by escribano - edit as needed
# Full reference: https://github.com/eduardosanzb/escribano#configuration

# === PERFORMANCE ===
ESCRIBANO_FRAME_WIDTH=1024          # Lower = faster (1920, 1280, 1024, 640)
ESCRIBANO_VLM_BATCH_SIZE=2          # 1-4 frames (lower = more reliable)
ESCRIBANO_SAMPLE_INTERVAL=10        # Base frame sampling (seconds)

# === QUALITY ===
ESCRIBANO_SCENE_THRESHOLD=0.4       # Scene detection sensitivity (0.0-1.0)
ESCRIBANO_VLM_MAX_TOKENS=2000       # Token budget per batch

# === MODELS ===
# ESCRIBANO_LLM_BACKEND=mlx             # LLM backend: 'mlx' (default) or 'ollama'
# ESCRIBANO_LLM_MODEL=qwen3.5:27b       # Ollama model (only used if llmBackend='ollama')
# ESCRIBANO_LLM_MLX_MODEL=              # MLX model (only used if llmBackend='mlx', auto-detected if not set)
ESCRIBANO_VLM_MODEL=mlx-community/Qwen3-VL-2B-Instruct-4bit

# === DEBUGGING ===
ESCRIBANO_VERBOSE=false              # Enable verbose logging
ESCRIBANO_DEBUG_VLM=false           # Debug VLM processing

# === ADVANCED ===
ESCRIBANO_SCENE_MIN_INTERVAL=2
ESCRIBANO_SAMPLE_GAP_THRESHOLD=15
ESCRIBANO_SAMPLE_GAP_FILL=3
ESCRIBANO_MLX_SOCKET_PATH=/tmp/escribano-mlx.sock
ESCRIBANO_MLX_STARTUP_TIMEOUT=60000
# ESCRIBANO_PYTHON_PATH=             # Auto-detected if not set
ESCRIBANO_ARTIFACT_THINK=false      # Enable thinking for artifacts (slower)

# === OPTIONAL (Outline publishing) ===
# ESCRIBANO_OUTLINE_URL=
# ESCRIBANO_OUTLINE_TOKEN=
# ESCRIBANO_OUTLINE_COLLECTION=Escribano Sessions
`;

// =============================================================================
// CONFIG LOADER
// =============================================================================

let cachedConfig: Config | null = null;

export function getConfigPath(): string {
  return path.join(homedir(), '.escribano', '.env');
}

export function createDefaultConfig(): void {
  const configDir = path.join(homedir(), '.escribano');
  const configPath = getConfigPath();

  try {
    if (!existsSync(configDir)) {
      mkdirSync(configDir, { recursive: true });
    }

    if (!existsSync(configPath)) {
      writeFileSync(configPath, CONFIG_TEMPLATE, 'utf-8');
      console.log(`Created config file at ${configPath}`);
      console.log('You can customize settings by editing this file.\n');
    }
  } catch (error) {
    console.error(
      `Failed to create config file at ${configPath}: ${(error as Error).message}`
    );
  }
}

export function loadConfig(): Config {
  if (cachedConfig) {
    return cachedConfig;
  }

  // 1. Load from config file (if exists)
  const configPath = getConfigPath();
  if (existsSync(configPath)) {
    try {
      const result = dotenvConfig({ path: configPath });
      if (result.error) {
        console.error(
          `Failed to parse config file ${configPath}: ${result.error.message}`
        );
        console.error('Using default configuration.');
      } else if (result.parsed && Object.keys(result.parsed).length > 0) {
        console.log(`Loaded config from ${configPath}`);
      }
    } catch (error) {
      console.error(
        `Error reading config file ${configPath}: ${(error as Error).message}`
      );
      console.error('Using default configuration.');
    }
  }

  // 2. Build config from environment variables
  const config: Config = {
    // === PERFORMANCE ===
    frameWidth: parseEnvNumber(
      'ESCRIBANO_FRAME_WIDTH',
      DEFAULT_CONFIG.frameWidth
    ),
    vlmBatchSize: parseEnvNumber(
      'ESCRIBANO_VLM_BATCH_SIZE',
      DEFAULT_CONFIG.vlmBatchSize
    ),
    sampleInterval: parseEnvNumber(
      'ESCRIBANO_SAMPLE_INTERVAL',
      DEFAULT_CONFIG.sampleInterval
    ),

    // === QUALITY ===
    sceneThreshold: parseEnvNumber(
      'ESCRIBANO_SCENE_THRESHOLD',
      DEFAULT_CONFIG.sceneThreshold
    ),
    vlmMaxTokens: parseEnvNumber(
      'ESCRIBANO_VLM_MAX_TOKENS',
      DEFAULT_CONFIG.vlmMaxTokens
    ),

    // === MODELS ===
    llmModel: process.env.ESCRIBANO_LLM_MODEL,
    llmBackend: (process.env.ESCRIBANO_LLM_BACKEND ??
      DEFAULT_CONFIG.llmBackend) as 'mlx' | 'ollama',
    llmMlxModel: process.env.ESCRIBANO_LLM_MLX_MODEL,
    vlmModel: process.env.ESCRIBANO_VLM_MODEL || DEFAULT_CONFIG.vlmModel,
    subjectGroupingModel: process.env.ESCRIBANO_SUBJECT_GROUPING_MODEL,

    // === DEBUGGING ===
    verbose: parseEnvBoolean('ESCRIBANO_VERBOSE', DEFAULT_CONFIG.verbose),
    debugOllama: parseEnvBoolean(
      'ESCRIBANO_DEBUG_OLLAMA',
      DEFAULT_CONFIG.debugOllama
    ),
    debugVlm: parseEnvBoolean('ESCRIBANO_DEBUG_VLM', DEFAULT_CONFIG.debugVlm),
    skipLlm: parseEnvBoolean('ESCRIBANO_SKIP_LLM', DEFAULT_CONFIG.skipLlm),

    // === ADVANCED ===
    sceneMinInterval: parseEnvNumber(
      'ESCRIBANO_SCENE_MIN_INTERVAL',
      DEFAULT_CONFIG.sceneMinInterval
    ),
    sampleGapThreshold: parseEnvNumber(
      'ESCRIBANO_SAMPLE_GAP_THRESHOLD',
      DEFAULT_CONFIG.sampleGapThreshold
    ),
    sampleGapFill: parseEnvNumber(
      'ESCRIBANO_SAMPLE_GAP_FILL',
      DEFAULT_CONFIG.sampleGapFill
    ),
    mlxSocketPath:
      process.env.ESCRIBANO_MLX_SOCKET_PATH || DEFAULT_CONFIG.mlxSocketPath,
    mlxStartupTimeout: parseEnvNumber(
      'ESCRIBANO_MLX_STARTUP_TIMEOUT',
      DEFAULT_CONFIG.mlxStartupTimeout
    ),
    pythonPath: process.env.ESCRIBANO_PYTHON_PATH,
    parallelTranscription: parseEnvBoolean(
      'ESCRIBANO_PARALLEL_TRANSCRIPTION',
      DEFAULT_CONFIG.parallelTranscription
    ),
    artifactThink: parseEnvBoolean(
      'ESCRIBANO_ARTIFACT_THINK',
      DEFAULT_CONFIG.artifactThink
    ),

    // === OPTIONAL ===
    outlineUrl: process.env.ESCRIBANO_OUTLINE_URL,
    outlineToken: process.env.ESCRIBANO_OUTLINE_TOKEN,
    outlineCollection:
      process.env.ESCRIBANO_OUTLINE_COLLECTION ||
      DEFAULT_CONFIG.outlineCollection,
  };

  // 3. Validate with Zod
  const validated = configSchema.parse(config);

  cachedConfig = validated;
  return validated;
}

// =============================================================================
// HELPERS
// =============================================================================

function parseEnvNumber(key: string, defaultValue: number): number {
  const value = process.env[key];
  if (!value) return defaultValue;

  const parsed = Number(value);
  if (Number.isNaN(parsed)) {
    console.warn(`Invalid ${key}="${value}", using default: ${defaultValue}`);
    return defaultValue;
  }

  return parsed;
}

function parseEnvBoolean(key: string, defaultValue: boolean): boolean {
  const value = process.env[key];
  if (!value) return defaultValue;

  return value === 'true';
}

// =============================================================================
// CLI UTILITIES
// =============================================================================

export function showConfig(): void {
  const configPath = getConfigPath();

  // Create config file if it doesn't exist
  if (!existsSync(configPath)) {
    createDefaultConfig();
  }

  const config = loadConfig();

  console.log(`Config file: ${configPath}\n`);
  console.log('Current configuration:');
  console.log(JSON.stringify(config, null, 2));
}

export function showConfigPath(): void {
  const configPath = getConfigPath();

  // Create config file if it doesn't exist
  if (!existsSync(configPath)) {
    createDefaultConfig();
  }

  console.log(configPath);
}
