/**
 * Configuration Management
 *
 * Loads configuration from multiple sources with priority (highest to lowest):
 * 1. CLI arguments
 * 2. Shell environment variables (export ESCRIBANO_*)
 * 3. ~/.escribano/.env file
 * 4. RAM-aware defaults (based on system memory)
 *
 * Note: Project-level .env is NOT loaded by default (only for development).
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir, totalmem } from 'node:os';
import path from 'node:path';
import { config as dotenvConfig } from 'dotenv';
import { z } from 'zod';

// =============================================================================
// CONFIG SCHEMA
// =============================================================================

const configSchema = z.object({
  // === PERFORMANCE ===
  frameWidth: z.number().int().min(320).max(3840).default(1024),
  vlmBatchSize: z.number().int().min(1).max(8).default(2),
  sampleInterval: z.number().int().min(1).max(60).default(10),

  // === QUALITY ===
  sceneThreshold: z.number().min(0).max(1).default(0.4),
  vlmMaxTokens: z.number().int().min(500).max(8000).default(2000),

  // === MODELS ===
  llmModel: z.string().optional(),
  vlmModel: z.string().default('mlx-community/Qwen3-VL-2B-Instruct-4bit'),
  subjectGroupingModel: z.string().optional(),

  // === DEBUGGING ===
  verbose: z.boolean().default(false),
  debugOllama: z.boolean().default(false),
  debugVlm: z.boolean().default(false),
  skipLlm: z.boolean().default(false),

  // === ADVANCED ===
  sceneMinInterval: z.number().int().min(1).max(10).default(2),
  sampleGapThreshold: z.number().int().min(5).max(60).default(15),
  sampleGapFill: z.number().int().min(1).max(10).default(3),
  mlxSocketPath: z.string().default('/tmp/escribano-mlx.sock'),
  mlxStartupTimeout: z.number().int().min(10000).default(120000),
  pythonPath: z.string().optional(),
  parallelTranscription: z.boolean().default(false),
  artifactThink: z.boolean().default(false),

  // === OPTIONAL (Outline publishing) ===
  outlineUrl: z.string().optional(),
  outlineToken: z.string().optional(),
  outlineCollection: z.string().default('Escribano Sessions'),
});

export type Config = z.infer<typeof configSchema>;

export interface ConfigSource {
  key: string;
  source: 'env' | 'default' | 'ram-aware';
}

// =============================================================================
// RAM DETECTION
// =============================================================================

function getSystemRamGB(): number {
  return Math.round(totalmem() / (1024 * 1024 * 1024));
}

function getRamTier(ramGB: number): { tier: string; frameWidth: number } {
  if (ramGB >= 32) {
    return { tier: 'high', frameWidth: 1024 };
  }
  if (ramGB >= 16) {
    return { tier: 'medium', frameWidth: 1024 };
  }
  return { tier: 'low', frameWidth: 768 };
}

// =============================================================================
// DEFAULT CONFIG
// =============================================================================

const BASE_DEFAULTS = {
  frameWidth: 1024,
  vlmBatchSize: 2,
  sampleInterval: 10,
  sceneThreshold: 0.4,
  vlmMaxTokens: 2000,
  vlmModel: 'mlx-community/Qwen3-VL-2B-Instruct-4bit',
  verbose: false,
  debugOllama: false,
  debugVlm: false,
  skipLlm: false,
  sceneMinInterval: 2,
  sampleGapThreshold: 15,
  sampleGapFill: 3,
  mlxSocketPath: '/tmp/escribano-mlx.sock',
  mlxStartupTimeout: 120000,
  parallelTranscription: false,
  artifactThink: false,
  outlineCollection: 'Escribano Sessions',
};

// =============================================================================
// CONFIG FILE TEMPLATE
// =============================================================================

const CONFIG_TEMPLATE = `# Escribano Configuration - ~/.escribano/.env
# Generated by escribano - edit as needed
# Full reference: https://github.com/eduardosanzb/escribano#configuration

# === PERFORMANCE ===
# ESCRIBANO_FRAME_WIDTH=1024          # Auto-adjusted based on RAM (1024 for 16GB+, 768 for <16GB)
# ESCRIBANO_VLM_BATCH_SIZE=2          # 1-4 frames (lower = more reliable)
ESCRIBANO_SAMPLE_INTERVAL=10          # Base frame sampling (seconds)

# === QUALITY ===
ESCRIBANO_SCENE_THRESHOLD=0.4         # Scene detection sensitivity (0.0-1.0)
ESCRIBANO_VLM_MAX_TOKENS=2000         # Token budget per batch

# === MODELS ===
# ESCRIBANO_LLM_MODEL=qwen3.5:27b     # Summary generation (auto-detected if not set)
ESCRIBANO_VLM_MODEL=mlx-community/Qwen3-VL-2B-Instruct-4bit

# === DEBUGGING ===
ESCRIBANO_VERBOSE=false               # Enable verbose logging
ESCRIBANO_DEBUG_VLM=false             # Debug VLM processing

# === ADVANCED ===
ESCRIBANO_SCENE_MIN_INTERVAL=2
ESCRIBANO_SAMPLE_GAP_THRESHOLD=15
ESCRIBANO_SAMPLE_GAP_FILL=3
ESCRIBANO_MLX_SOCKET_PATH=/tmp/escribano-mlx.sock
ESCRIBANO_MLX_STARTUP_TIMEOUT=120000
# ESCRIBANO_PYTHON_PATH=              # Auto-detected if not set
ESCRIBANO_ARTIFACT_THINK=false        # Enable thinking for artifacts (slower)

# === OPTIONAL (Outline publishing) ===
# ESCRIBANO_OUTLINE_URL=
# ESCRIBANO_OUTLINE_TOKEN=
# ESCRIBANO_OUTLINE_COLLECTION=Escribano Sessions
`;

// =============================================================================
// CONFIG LOADER
// =============================================================================

let cachedConfig: Config | null = null;
let cachedSources: ConfigSource[] = [];

export function getConfigPath(): string {
  return path.join(homedir(), '.escribano', '.env');
}

export function createDefaultConfig(): void {
  const configDir = path.join(homedir(), '.escribano');
  const configPath = getConfigPath();

  try {
    if (!existsSync(configDir)) {
      mkdirSync(configDir, { recursive: true });
    }

    if (!existsSync(configPath)) {
      writeFileSync(configPath, CONFIG_TEMPLATE, 'utf-8');
      console.log(`Created config file at ${configPath}`);
      console.log('You can customize settings by editing this file.\n');
    }
  } catch (error) {
    console.error(
      `Failed to create config file at ${configPath}: ${(error as Error).message}`
    );
  }
}

/**
 * Check if running in development mode.
 * Development mode = running via tsx from source (src/index.ts)
 * Production mode = running compiled code (dist/index.js)
 */
function isDevelopmentMode(): boolean {
  // Check if running from src directory via tsx
  const currentFile = import.meta.url;
  return currentFile.includes('/src/');
}

export function loadConfig(): Config {
  if (cachedConfig) {
    return cachedConfig;
  }

  const sources: ConfigSource[] = [];

  // 1. Load from user config file (PRODUCTION MODE ONLY)
  // In development mode, we use project .env via tsx --env-file flag
  if (!isDevelopmentMode()) {
    const configPath = getConfigPath();
    if (existsSync(configPath)) {
      try {
        const result = dotenvConfig({ path: configPath });
        if (result.error) {
          console.error(
            `Failed to parse config file ${configPath}: ${result.error.message}`
          );
          console.error('Using default configuration.');
        } else if (result.parsed && Object.keys(result.parsed).length > 0) {
          console.log(`Loaded config from ${configPath}`);
        }
      } catch (error) {
        console.error(
          `Error reading config file ${configPath}: ${(error as Error).message}`
        );
        console.error('Using default configuration.');
      }
    }
  }

  // 2. Get RAM-aware defaults
  const ramGB = getSystemRamGB();
  const ramTier = getRamTier(ramGB);

  // 3. Build config with source tracking
  const config: Config = {
    // === PERFORMANCE ===
    frameWidth: parseEnvNumberWithSource(
      'ESCRIBANO_FRAME_WIDTH',
      ramTier.frameWidth,
      sources,
      'frameWidth'
    ),
    vlmBatchSize: parseEnvNumberWithSource(
      'ESCRIBANO_VLM_BATCH_SIZE',
      BASE_DEFAULTS.vlmBatchSize,
      sources,
      'vlmBatchSize'
    ),
    sampleInterval: parseEnvNumberWithSource(
      'ESCRIBANO_SAMPLE_INTERVAL',
      BASE_DEFAULTS.sampleInterval,
      sources,
      'sampleInterval'
    ),

    // === QUALITY ===
    sceneThreshold: parseEnvNumberWithSource(
      'ESCRIBANO_SCENE_THRESHOLD',
      BASE_DEFAULTS.sceneThreshold,
      sources,
      'sceneThreshold'
    ),
    vlmMaxTokens: parseEnvNumberWithSource(
      'ESCRIBANO_VLM_MAX_TOKENS',
      BASE_DEFAULTS.vlmMaxTokens,
      sources,
      'vlmMaxTokens'
    ),

    // === MODELS ===
    llmModel: parseEnvStringWithSource(
      'ESCRIBANO_LLM_MODEL',
      undefined,
      sources,
      'llmModel'
    ),
    vlmModel: parseEnvStringWithSource(
      'ESCRIBANO_VLM_MODEL',
      BASE_DEFAULTS.vlmModel,
      sources,
      'vlmModel'
    ) as string,
    subjectGroupingModel: parseEnvStringWithSource(
      'ESCRIBANO_SUBJECT_GROUPING_MODEL',
      undefined,
      sources,
      'subjectGroupingModel'
    ),

    // === DEBUGGING ===
    verbose: parseEnvBooleanWithSource(
      'ESCRIBANO_VERBOSE',
      BASE_DEFAULTS.verbose,
      sources,
      'verbose'
    ),
    debugOllama: parseEnvBooleanWithSource(
      'ESCRIBANO_DEBUG_OLLAMA',
      BASE_DEFAULTS.debugOllama,
      sources,
      'debugOllama'
    ),
    debugVlm: parseEnvBooleanWithSource(
      'ESCRIBANO_DEBUG_VLM',
      BASE_DEFAULTS.debugVlm,
      sources,
      'debugVlm'
    ),
    skipLlm: parseEnvBooleanWithSource(
      'ESCRIBANO_SKIP_LLM',
      BASE_DEFAULTS.skipLlm,
      sources,
      'skipLlm'
    ),

    // === ADVANCED ===
    sceneMinInterval: parseEnvNumberWithSource(
      'ESCRIBANO_SCENE_MIN_INTERVAL',
      BASE_DEFAULTS.sceneMinInterval,
      sources,
      'sceneMinInterval'
    ),
    sampleGapThreshold: parseEnvNumberWithSource(
      'ESCRIBANO_SAMPLE_GAP_THRESHOLD',
      BASE_DEFAULTS.sampleGapThreshold,
      sources,
      'sampleGapThreshold'
    ),
    sampleGapFill: parseEnvNumberWithSource(
      'ESCRIBANO_SAMPLE_GAP_FILL',
      BASE_DEFAULTS.sampleGapFill,
      sources,
      'sampleGapFill'
    ),
    mlxSocketPath: parseEnvStringWithSource(
      'ESCRIBANO_MLX_SOCKET_PATH',
      BASE_DEFAULTS.mlxSocketPath,
      sources,
      'mlxSocketPath'
    ) as string,
    mlxStartupTimeout: parseEnvNumberWithSource(
      'ESCRIBANO_MLX_STARTUP_TIMEOUT',
      BASE_DEFAULTS.mlxStartupTimeout,
      sources,
      'mlxStartupTimeout'
    ),
    pythonPath: parseEnvStringWithSource(
      'ESCRIBANO_PYTHON_PATH',
      undefined,
      sources,
      'pythonPath'
    ),
    parallelTranscription: parseEnvBooleanWithSource(
      'ESCRIBANO_PARALLEL_TRANSCRIPTION',
      BASE_DEFAULTS.parallelTranscription,
      sources,
      'parallelTranscription'
    ),
    artifactThink: parseEnvBooleanWithSource(
      'ESCRIBANO_ARTIFACT_THINK',
      BASE_DEFAULTS.artifactThink,
      sources,
      'artifactThink'
    ),

    // === OPTIONAL ===
    outlineUrl: parseEnvStringWithSource(
      'ESCRIBANO_OUTLINE_URL',
      undefined,
      sources,
      'outlineUrl'
    ),
    outlineToken: parseEnvStringWithSource(
      'ESCRIBANO_OUTLINE_TOKEN',
      undefined,
      sources,
      'outlineToken'
    ),
    outlineCollection: parseEnvStringWithSource(
      'ESCRIBANO_OUTLINE_COLLECTION',
      BASE_DEFAULTS.outlineCollection,
      sources,
      'outlineCollection'
    ) as string,
  };

  // 4. Validate with Zod
  const validated = configSchema.parse(config);

  cachedConfig = validated;
  cachedSources = sources;
  return validated;
}

export function getConfigSources(): ConfigSource[] {
  return cachedSources;
}

export function getRamInfo(): { ramGB: number; tier: string } {
  const ramGB = getSystemRamGB();
  const ramTier = getRamTier(ramGB);
  return { ramGB, tier: ramTier.tier };
}

// =============================================================================
// HELPERS
// =============================================================================

function parseEnvNumberWithSource(
  key: string,
  defaultValue: number,
  sources: ConfigSource[],
  configKey: string
): number {
  const value = process.env[key];
  if (value === undefined) {
    const isRamAware = configKey === 'frameWidth';
    sources.push({
      key: configKey,
      source: isRamAware ? 'ram-aware' : 'default',
    });
    return defaultValue;
  }

  const parsed = Number(value);
  if (Number.isNaN(parsed)) {
    console.warn(`Invalid ${key}="${value}", using default: ${defaultValue}`);
    sources.push({ key: configKey, source: 'default' });
    return defaultValue;
  }

  sources.push({ key: configKey, source: 'env' });
  return parsed;
}

function parseEnvStringWithSource(
  key: string,
  defaultValue: string | undefined,
  sources: ConfigSource[],
  configKey: string
): string | undefined {
  const value = process.env[key];
  if (value === undefined) {
    sources.push({ key: configKey, source: 'default' });
    return defaultValue;
  }

  sources.push({ key: configKey, source: 'env' });
  return value;
}

function parseEnvBooleanWithSource(
  key: string,
  defaultValue: boolean,
  sources: ConfigSource[],
  configKey: string
): boolean {
  const value = process.env[key];
  if (value === undefined) {
    sources.push({ key: configKey, source: 'default' });
    return defaultValue;
  }

  sources.push({ key: configKey, source: 'env' });
  return value === 'true';
}

// =============================================================================
// LOGGING
// =============================================================================

export function logConfig(): void {
  const config = loadConfig();
  const { ramGB, tier } = getRamInfo();
  const sources = getConfigSources();

  const userSetKeys = sources.filter((s) => s.source === 'env');

  // Compact one-liner per category
  const perf = `frameWidth=${config.frameWidth} vlmBatchSize=${config.vlmBatchSize} sampleInterval=${config.sampleInterval}`;
  const quality = `sceneThreshold=${config.sceneThreshold} vlmMaxTokens=${config.vlmMaxTokens}`;
  const models = `vlmModel=${config.vlmModel.split('/').pop()} llmModel=${config.llmModel || 'auto'}`;

  // Show dev mode indicator if applicable
  if (isDevelopmentMode()) {
    console.log('[Config] Mode: development (using project .env)');
  }

  console.log(`[Config] RAM: ${ramGB}GB (${tier})`);
  console.log(`[Config] Performance: ${perf}`);
  console.log(`[Config] Quality: ${quality}`);
  console.log(`[Config] Models: ${models}`);

  if (userSetKeys.length > 0) {
    console.log(
      `[Config] User overrides: ${userSetKeys.map((s) => s.key).join(', ')}`
    );
  }
}

// =============================================================================
// CLI UTILITIES
// =============================================================================

export function showConfig(): void {
  const configPath = getConfigPath();

  // In dev mode, show that we're using project .env instead
  if (isDevelopmentMode()) {
    console.log(
      'Development mode: Using project .env (not ~/.escribano/.env)\n'
    );
    console.log('Current configuration:');
    const config = loadConfig();
    console.log(JSON.stringify(config, null, 2));
    return;
  }

  // Create config file if it doesn't exist (production mode)
  if (!existsSync(configPath)) {
    createDefaultConfig();
  }

  const config = loadConfig();
  const { ramGB, tier } = getRamInfo();

  console.log(`Config file: ${configPath}`);
  console.log(`System RAM: ${ramGB}GB (${tier} tier)\n`);
  console.log('Current configuration:');
  console.log(JSON.stringify(config, null, 2));
}

export function showConfigPath(): void {
  const configPath = getConfigPath();

  // Create config file if it doesn't exist
  if (!existsSync(configPath)) {
    createDefaultConfig();
  }

  console.log(configPath);
}
